#ifndef WIZSERVICE_GLOBAL_H
#define WIZSERVICE_GLOBAL_H

#include <QtGlobal>

#if defined(WIZSERVICE_LIBRARY)
#  define WIZSERVICE_EXPORT Q_DECL_EXPORT
#else
#  define WIZSERVICE_EXPORT Q_DECL_IMPORT
#endif

#endif // WIZSERVICE_GLOBAL_H
